# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.14.5"

  depends_on "mkcert"

  on_macos do
    on_intel do
      url "https://github.com/openrundev/openrun/releases/download/v0.14.5/openrun-v0.14.5-darwin-amd64.tar.gz"
      sha256 "d75d70b42b47e02f40227a6aa897f0c1b8185fc74a1167f1945967e89470d623"

      def install
        bin.install "openrun"
      end
    end
    on_arm do
      url "https://github.com/openrundev/openrun/releases/download/v0.14.5/openrun-v0.14.5-darwin-arm64.tar.gz"
      sha256 "e83afb152fc365ae4a37cdf7416368ea4d28ec4856d6f2e3f9e949330b34034b"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openrundev/openrun/releases/download/v0.14.5/openrun-v0.14.5-linux-amd64.tar.gz"
        sha256 "710c186351d1bbfd3e78e95c3ef23c67412b337d974cc86ad348e873dbf0c799"

        def install
          bin.install "openrun"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openrundev/openrun/releases/download/v0.14.5/openrun-v0.14.5-linux-arm64.tar.gz"
        sha256 "d10c6c0f4c4eb6891fd5b67273818afe52b1dc60ef05da971379cf87d9c24caf"

        def install
          bin.install "openrun"
        end
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
