# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.15.19"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openrundev/openrun/releases/download/v0.15.19/openrun-v0.15.19-darwin-amd64.tar.gz"
      sha256 "704caa50b4acd241c7097864449568bc037974b8b3e81c7d325ec7069104a379"

      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openrundev/openrun/releases/download/v0.15.19/openrun-v0.15.19-darwin-arm64.tar.gz"
      sha256 "dfc9107c0a348265b60209561394245789b19eabbc8d438ef39a7914e11682b1"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.15.19/openrun-v0.15.19-linux-amd64.tar.gz"
      sha256 "894d9b7e829849e8ae9b4e20d988c38c905b93adec638a2a49815ec0f7ef3014"
      def install
        bin.install "openrun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openrundev/openrun/releases/download/v0.15.19/openrun-v0.15.19-linux-arm64.tar.gz"
      sha256 "892c4c0247cdd3ef4d9f4f159c462511e87fb210024bf451a10c3953d9390adf"
      def install
        bin.install "openrun"
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
