# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openrun < Formula
  desc ""
  homepage "https://openrun.dev"
  version "0.15.2"

  depends_on "mkcert"

  on_macos do
    on_intel do
      url "https://github.com/openrundev/openrun/releases/download/v0.15.2/openrun-v0.15.2-darwin-amd64.tar.gz"
      sha256 "3d9d3d957c8aabdf6d77134bad24d522cb219c576542d66c3e8d0ec4e9b226ae"

      def install
        bin.install "openrun"
      end
    end
    on_arm do
      url "https://github.com/openrundev/openrun/releases/download/v0.15.2/openrun-v0.15.2-darwin-arm64.tar.gz"
      sha256 "b60a75d571b06a955ecd91ef5199e49a96604e161c8dd273f55fa19c15fe1113"

      def install
        bin.install "openrun"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openrundev/openrun/releases/download/v0.15.2/openrun-v0.15.2-linux-amd64.tar.gz"
        sha256 "29e22a3ea9f7e2d5f72e57c9459f986e45b38c021c5ba8fb906424f9188a1c30"

        def install
          bin.install "openrun"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/openrundev/openrun/releases/download/v0.15.2/openrun-v0.15.2-linux-arm64.tar.gz"
        sha256 "29e6da342f2e588f8093c0623862766211e138cb9e87f4a5aca7ac2f45219cac"

        def install
          bin.install "openrun"
        end
      end
    end
  end

  def post_install
    unless File.exist?("#{etc}/openrun.toml")
      pid = spawn("#{opt_bin}/openrun password", out: "#{etc}/openrun.toml")
      puts "********** Initializing \"admin\" user **********"
      Process.wait(pid)
      puts "************* Save this password ****************"

      mkcert_path = `which mkcert`.chomp
      unless mkcert_path.empty?
        system("mkdir -p #{HOMEBREW_PREFIX}/var/openrun/config/certificates")
        system("#{mkcert_path} -install")
        system("#{mkcert_path} -cert-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.crt -key-file #{HOMEBREW_PREFIX}/var/openrun/config/certificates/default.key localhost 127.0.0.1 \"*.localhost\"")
        puts "Created localhost TLS certificates"
      end
    end
  end

  service do
    run [ opt_bin/"openrun", "server", "start" ]
    keep_alive true
    working_dir HOMEBREW_PREFIX
    log_path var/"log/openrun.log"
    error_log_path var/"log/openrun.log"
  end
end
